# Generated by Django 3.1.5 on 2023-11-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231110_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
