# Generated by Django 3.1.5 on 2023-11-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prebody',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
